### ISSUE TITLE
Can thi be used outside of init phase?

### ISSUE THREAD

**Issue by s3rj1k** [acuenca-facephi/xk6-read#5]
Hi, just to clarify a bit, can this extension be used outside of init phase, for example to read file per every request that `k6` does?

I am bit new to `k6` so I apologies for probably asking obvious question here :)

**Comment by acuenca-facephi** [comment]
> Hi, just to clarify a bit, can this extension be used outside of init phase, for example to read file per every request that `k6` does?
> 
> I am bit new to `k6` so I apologies for probably asking obvious question here :)

Yes, you can!
I created this extension because K6, by default, can only [read files in the init stage](https://k6.io/docs/javascript-api/init-context/open/).
In my usecase, I use the extension to read files during _setup stage_:
```javascript
import encoding from 'k6/encoding';
import read from 'k6/x/read';

...

function prepareBase64Images() {
    const BASE64_FILES = new Array();
    const DIRECTORY = read.readDirectory(FILES_DIRECTORY_PATH);
    for (let i = 0; i < DIRECTORY.content.length && i < FILES_LIMIT; i++) {
        BASE64_FILES.push(new Array());
        for (let j = 0; j < DIRECTORY.content[i].content.length; j++) {
            const BASE64_FILE = encoding.b64encode(DIRECTORY.content[i].content[j].content);
            BASE64_FILES[i].push(BASE64_FILE);
        }
    }
    return BASE64_FILES;
}

...

export function setup() {
    ...

    const BASE64_FILES = prepareBase64Images();

    ...

    return {
        ...,
        BASE64_FILES: BASE64_FILES
    };
}
```

Note that I have a specific directory structure and need the files in base64 strings, so I iterate over a directory with subdirectories.

Hope this helps you.
